config/routes.rb
Rails.application.routes.draw do
  resources :detalles
  resources :multa
  resources :prestamos
  resources :usuarios
  resources :libros
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'consulta/index'
  post 'consulta/buscar'
  get 'prestamos/consulta'
  root to: 'main#index'
end

app/models/detalle.rb
class Detalle < ApplicationRecord
  belongs_to :Prestamo
  belongs_to :Libros
end

app/controllers/detalles_controller.rb
class DetallesController < ApplicationController
  before_action :set_detalle, only: %i[ show edit update destroy ]

  # GET /detalles or /detalles.json
  def index
    @detalles = Detalle.all
  end

  # GET /detalles/1 or /detalles/1.json
  def show
  end

  # GET /detalles/new
  def new
    @detalle = Detalle.new
  end

  # GET /detalles/1/edit
  def edit
  end

  # POST /detalles or /detalles.json
  def create
    @detalle = Detalle.new(detalle_params)

    respond_to do |format|
      if @detalle.save
        format.html { redirect_to detalle_url(@detalle), notice: "Detalle was successfully created." }
        format.json { render :show, status: :created, location: @detalle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @detalle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /detalles/1 or /detalles/1.json
  def update
    respond_to do |format|
      if @detalle.update(detalle_params)
        format.html { redirect_to detalle_url(@detalle), notice: "Detalle was successfully updated." }
        format.json { render :show, status: :ok, location: @detalle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @detalle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /detalles/1 or /detalles/1.json
  def destroy
    @detalle.destroy

    respond_to do |format|
      format.html { redirect_to detalles_url, notice: "Detalle was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detalle
      @detalle = Detalle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def detalle_params
      params.require(:detalle).permit(:cantidad, :Prestamo_id, :Libros_id)
    end
end

app/helpers/detalles_helper.rb
module DetallesHelper
end

app/views/detalles/_detalle.html.erb
<div id="<%= dom_id detalle %>">
  <p>
    <strong>Cantidad:</strong>
    <%= detalle.cantidad %>
  </p>

  <p>
    <strong>Prestamo:</strong>
    <%= detalle.Prestamo_id %>
  </p>

  <p>
    <strong>Libros:</strong>
    <%= detalle.Libros_id %>
  </p>

</div>

app/views/detalles/_form.html.erb
<%= form_with(model: detalle) do |form| %>
  <% if detalle.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(detalle.errors.count, "error") %> prohibited this detalle from being saved:</h2>

      <ul>
        <% detalle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cantidad, style: "display: block" %>
    <%= form.number_field :cantidad %>
  </div>

  <div>
    <%= form.label :Prestamo_id, style: "display: block" %>
    <!--<%= form.select :Prestamo_id, options_for_select(Prestamo.all.map{|s|[s.feha, s.id]}) %>-->
    <%= form.text_field :Prestamo_id %>
  </div>

  <div>
    <%= form.label :Libros_id, style: "display: block" %>
    <!--<%= form.select :Libros_id, options_for_select(Libro.all.map{|s|[s.titulo, s.id]}) %>-->
    <%= form.text_field :Libros_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/detalles/edit.html.erb
<h1>Editing detalle</h1>

<%= render "form", detalle: @detalle %>

<br>

<div>
  <%= link_to "Show this detalle", @detalle %> |
  <%= link_to "Back to detalles", detalles_path %>
</div>

app/views/detalles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Detalles</h1>

<div id="detalles">
  <% @detalles.each do |detalle| %>
    <%= render detalle %>
    <p>
      <%= link_to "Show this detalle", detalle %>
    </p>
  <% end %>
</div>

<%= link_to "New detalle", new_detalle_path %>

app/views/detalles/new.html.erb
<h1>New detalle</h1>

<%= render "form", detalle: @detalle %>

<br>

<div>
  <%= link_to "Back to detalles", detalles_path %>
</div>

app/views/detalles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @detalle %>

<div>
  <%= link_to "Edit this detalle", edit_detalle_path(@detalle) %> |
  <%= link_to "Back to detalles", detalles_path %>

  <%= button_to "Destroy this detalle", @detalle, method: :delete %>
</div>