config/routes.rb
Rails.application.routes.draw do
  resources :detalles
  resources :multa
  resources :prestamos
  resources :usuarios
  resources :libros
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'consulta/index'
  post 'consulta/buscar'
  get 'prestamos/consulta'
  root to: 'main#index'
end

app/models/prestamo.rb
class Prestamo < ApplicationRecord
  belongs_to :Usuario
end

app/controllers/prestamos_controller.rb
class PrestamosController < ApplicationController
  before_action :set_prestamo, only: %i[ show edit update destroy ]

  # GET /prestamos or /prestamos.json
  def index
    @prestamos = Prestamo.all
  end

  # GET /prestamos/1 or /prestamos/1.json
  def show
  end

  # GET /prestamos/new
  def new
    @prestamo = Prestamo.new
  end

  # GET /prestamos/1/edit
  def edit
  end

  # POST /prestamos or /prestamos.json
  def create
    @prestamo = Prestamo.new(prestamo_params)

    respond_to do |format|
      if @prestamo.save
        format.html { redirect_to prestamo_url(@prestamo), notice: "Prestamo was successfully created." }
        format.json { render :show, status: :created, location: @prestamo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prestamo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prestamos/1 or /prestamos/1.json
  def update
    respond_to do |format|
      if @prestamo.update(prestamo_params)
        format.html { redirect_to prestamo_url(@prestamo), notice: "Prestamo was successfully updated." }
        format.json { render :show, status: :ok, location: @prestamo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prestamo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prestamos/1 or /prestamos/1.json
  def destroy
    @prestamo.destroy

    respond_to do |format|
      format.html { redirect_to prestamos_url, notice: "Prestamo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prestamo
      @prestamo = Prestamo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prestamo_params
      params.require(:prestamo).permit(:feha, :estado, :Usuario_id)
    end
end

def buscar
  @post = params[:Usuario_id]
  if @post
    @post = @prestamo.where(:Usuario_id => @bus)
  end
end

app/helpers/prestamos_helper.rb
module PrestamosHelper
end

app/views/prestamos/_form.html.erb
<%= form_with(model: prestamo) do |form| %>
  <% if prestamo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(prestamo.errors.count, "error") %> prohibited this prestamo from being saved:</h2>

      <ul>
        <% prestamo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :feha, style: "display: block" %>
    <%= form.date_field :feha %>
  </div>

  <div>
    <%= form.label :estado, style: "display: block" %>
    <%= form.number_field :estado %>
  </div>

  <div>
    <%= form.label :Usuario_id, style: "display: block" %>
   <%= form.select :Usuario_id, options_for_select(Usuario.all.map{|s|[s.nombre + ' ' + s.apellido, s.id]}) %>
    <!--<%= form.text_field :Usuario_id %>-->
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/prestamos/_prestamo.html.erb
<div id="<%= dom_id prestamo %>">
  <p>
    <strong>Fecha</strong>
    <%= prestamo.feha %>
  </p>

  <p>
    <strong>Estado:</strong>
    <%= prestamo.estado %>
  </p>

  <p>
    <strong>Usuario:</strong>
    <%= prestamo.Usuario_id.to_s + '-' + prestamo.Usuario.nombre + ' ' + prestamo.Usuario.apellido %>
  </p>

</div>

app/views/prestamos/edit.html.erb
<h1>Editing prestamo</h1>

<%= render "form", prestamo: @prestamo %>

<br>

<div>
  <%= link_to "Show this prestamo", @prestamo %> |
  <%= link_to "Back to prestamos", prestamos_path %>
</div>

app/views/prestamos/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
<h1>Prestamos</h1>
<br>
<%= link_to "New prestamo", new_prestamo_path, class: "btn btn-success btn-lg" %>
</div>
<br>
<div class="container">
  <div class="mx-auto">
  <table class="table table-striped">
    <thead>
        <tr>
            <td>ID</td>
            <td>Estado</td>
            <td>Fecha</td>
            <td>Ver Prestamo</td>
        </tr>
    </thead>
    <tbody>
    <% @prestamos.each do |prestamo| %>
        <tr>
             <td><%= prestamo.id %></td>
             <td><%= prestamo.estado %></td>
             <td><%= prestamo.feha %></td>
             <td><%= link_to "Ver prestamo", prestamo, class: "btn btn-warning" %></td>
        </tr>
         <% end %>
    </tbody>
    <tfood>
        <tr>
            <td>ID</td>
            <td>Estado</td>
            <td>Fecha</td>
            <td>Ver Prestamo</td>
        </tr>
    </tfood>
  </table>  
</div>
</div>

<div class="container">
  <div class="col-sm-6 mx-auto">
    <%= link_to "Consultar Prestamos de Libros", "/consulta/index", method: :get, class: "btn btn-info" %>

  </div>
</div> 

app/views/prestamos/new.html.erb
<h1>New prestamo</h1>

<%= render "form", prestamo: @prestamo %>

<br>

<div>
  <%= link_to "Back to prestamos", prestamos_path %>
</div>

app/views/prestamos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @prestamo %>

<div>
  <%= link_to "Edit this prestamo", edit_prestamo_path(@prestamo) %> |
  <%= link_to "Back to prestamos", prestamos_path %>

  <%= button_to "Destroy this prestamo", @prestamo, method: :delete %>
</div>