config/routes.rb
Rails.application.routes.draw do
  resources :detalles
  resources :multa
  resources :prestamos
  resources :usuarios
  resources :libros
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'consulta/index'
  post 'consulta/buscar'
  get 'prestamos/consulta'
  root to: 'main#index'
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: %i[ show edit update destroy ]

  # GET /usuarios or /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1 or /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios or /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario was successfully created." }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1 or /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario was successfully updated." }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1 or /usuarios/1.json
  def destroy
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: "Usuario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :apellido, :direccion, :telefono, :login, :password, :email, :or)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario) do |form| %>
  <% if usuario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% usuario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :apellido, style: "display: block" %>
    <%= form.text_field :apellido %>
  </div>

  <div>
    <%= form.label :direccion, style: "display: block" %>
    <%= form.text_field :direccion %>
  </div>

  <div>
    <%= form.label :telefono, style: "display: block" %>
    <%= form.text_field :telefono %>
  </div>

  <div>
    <%= form.label :login, style: "display: block" %>
    <%= form.text_field :login %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <!--
  <div>
    <%= form.label :or, style: "display: block" %>
    <%= form.text_field :or %>
  </div>
-->
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/usuarios/_usuario.html.erb
<div id="<%= dom_id usuario %>">
  <p>
    <strong>Nombre:</strong>
    <%= usuario.nombre %>
  </p>

  <p>
    <strong>Apellido:</strong>
    <%= usuario.apellido %>
  </p>

  <p>
    <strong>Direccion:</strong>
    <%= usuario.direccion %>
  </p>

  <p>
    <strong>Telefono:</strong>
    <%= usuario.telefono %>
  </p>

  <p>
    <strong>Login:</strong>
    <%= usuario.login %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= usuario.password %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= usuario.email %>
  </p>
<!--
  <p>
    <strong>Or:</strong>
    <%= usuario.or %>
  </p>
-->
</div>

app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render "form", usuario: @usuario %>

<br>

<div>
  <%= link_to "Show this usuario", @usuario %> |
  <%= link_to "Back to usuarios", usuarios_path %>
</div>

app/views/usuarios/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
<h1>Usuarios</h1>
<br><br>
<%= link_to "New Usuario",  new_usuario_path, class: "btn btn-success btn-lg" %>
</div>

<% @usuarios.each do |usuario| %>
<div id="usuarios">
<div class="row">
  <div class="col-md-4 mx-auto">
    <div class="card">
      <div class="card-body">
          <h5 class="card-tittle"><%= usuario.nombre + ' ' + usuario.apellido %></h5>
          <p class="card-text"><%= usuario.login %></p>
          <p class="card-text"><%= usuario.email %></p>
          <%= link_to "Show this Usuario", usuario, class: "btn btn-primary" %>
        </div>
      </div>
    </iv>
  </div>
</div>
<% end %>

app/views/usuarios/new.html.erb
<h1>New usuario</h1>

<%= render "form", usuario: @usuario %>

<br>

<div>
  <%= link_to "Back to usuarios", usuarios_path %>
</div>

app/views/usuarios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @usuario %>

<div>
  <%= link_to "Edit this usuario", edit_usuario_path(@usuario) %> |
  <%= link_to "Back to usuarios", usuarios_path %>

  <%= button_to "Destroy this usuario", @usuario, method: :delete %>
</div>