config/routes.rb
Rails.application.routes.draw do
  resources :detalles
  resources :multa
  resources :prestamos
  resources :usuarios
  resources :libros
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'consulta/index'
  post 'consulta/buscar'
  get 'prestamos/consulta'
  root to: 'main#index'
end

app/models/libro.rb
class Libro < ApplicationRecord
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  before_action :set_libro, only: %i[ show edit update destroy ]

  # GET /libros or /libros.json
  def index
    @libros = Libro.all
  end

  # GET /libros/1 or /libros/1.json
  def show
  end

  # GET /libros/new
  def new
    @libro = Libro.new
  end

  # GET /libros/1/edit
  def edit
  end

  # POST /libros or /libros.json
  def create
    @libro = Libro.new(libro_params)

    respond_to do |format|
      if @libro.save
        format.html { redirect_to libro_url(@libro), notice: "Libro was successfully created." }
        format.json { render :show, status: :created, location: @libro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libros/1 or /libros/1.json
  def update
    respond_to do |format|
      if @libro.update(libro_params)
        format.html { redirect_to libro_url(@libro), notice: "Libro was successfully updated." }
        format.json { render :show, status: :ok, location: @libro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libros/1 or /libros/1.json
  def destroy
    @libro.destroy

    respond_to do |format|
      format.html { redirect_to libros_url, notice: "Libro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libro
      @libro = Libro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def libro_params
      params.require(:libro).permit(:titulo, :autor, :anyo, :or)
    end
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/views/libros/_form.html.erb
<%= form_with(model: libro) do |form| %>
  <% if libro.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(libro.errors.count, "error") %> prohibited this libro from being saved:</h2>

      <ul>
        <% libro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :autor, style: "display: block" %>
    <%= form.text_field :autor %>
  </div>

  <div>
    <%= form.label :anyo, style: "display: block" %>
    <%= form.number_field :anyo %>
  </div>
  <!--
  <div>
    <%= form.label :or, style: "display: block" %>
    <%= form.text_field :or %>
  </div>
  -->
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/libros/_libro.html.erb
<div id="<%= dom_id libro %>">
  <p>
    <strong>Titulo:</strong>
    <%= libro.titulo %>
  </p>

  <p>
    <strong>Autor:</strong>
    <%= libro.autor %>
  </p>

  <p>
    <strong>Anyo:</strong>
    <%= libro.anyo %>
  </p>
<!--
  <p>
    <strong>Or:</strong>
    <%= libro.or %>
  </p>
-->  
</div>

app/views/libros/edit.html.erb
<h1>Editing libro</h1>

<%= render "form", libro: @libro %>

<br>

<div>
  <%= link_to "Show this libro", @libro %> |
  <%= link_to "Back to libros", libros_path %>
</div>

app/views/libros/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
<h1>Libros</h1>
<br><br>
<%= link_to "New libro", new_libro_path, class: "btn btn-success btn-lg" %>
</div>

<% @libros.each do |libro| %>
<div id="libros">
<div class="row">
  <div class="col-md-4 mx-auto">
    <div class="card">
      <div class="card-body">
          <h5 class="card-tittle"><%= libro.titulo %></h5>
          <p class="card-text"><%= libro.autor %></p>
          <p class="card-text"><%= libro.anyo %></p>
          <%= link_to "Show this libro", libro, class: "btn btn-primary" %>
        </div>
      </div>
    </iv>
  </div>
</div>
<% end %>

app/views/libros/new.html.erb
<h1>New libro</h1>

<%= render "form", libro: @libro %>

<br>

<div>
  <%= link_to "Back to libros", libros_path %>
</div>

app/views/libros/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @libro %>

<div>
  <%= link_to "Edit this libro", edit_libro_path(@libro) %> |
  <%= link_to "Back to libros", libros_path %>

  <%= button_to "Destroy this libro", @libro, method: :delete %>
</div>